In [2]:
import torch

In [16]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
x.shape

torch.Size([12])

In [18]:
x.numel()

12

In [19]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
torch.zeros(3,4,5)

In [20]:
torch.ones(3,4,5)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

**有几个方括号就是几维的**

In [21]:
torch.tensor([[1,2,3],[2,3,4],[3,4,5]])

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

## tensor的运算

In [22]:
x = torch.tensor([1,2,3])
y = torch.tensor([3,3,4])
x+y,x-y

(tensor([4, 5, 7]), tensor([-2, -1, -1]))

## tensor张量的链接  

**使用torch.cat**  
>dim=0是行连接 就是列数不变，叠加行   
dim=2是列连接  就是行数不变，叠加列

In [19]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))#生成一个12个元素的张量，浮点类型，重组成3，4的矩阵格式
y = torch.tensor([[2.0,1,2,3],[1,2,3,4],[3,4,5,6]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)#要放到同一行且用逗号隔开才能显示两个结果

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  2.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 3.,  4.,  5.,  6.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  3.,  4.,  5.,  6.]]))

## 通过逻辑运算符，构建tensor张量

In [11]:
x==y

tensor([[False,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

## 使用sum对张量里的所有元素求和  
**结果得到的是只有一个元素的张量**

In [12]:
x.sum()

tensor(66.)

## 广播机制  
>**使得形状不同的张量也能够执行元素操作**

In [24]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b#想要同时显示两个元素，只能这样

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 数据读取

>**-1**:   选择最后一个元素  
>**1:3**:  选择第一和第二个元素
>>因为从0开始，所以，1是第二个，同时1:3是不包含3的

In [25]:
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

## 数据写入

In [27]:
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
x[0:2,:]=12#把第一行第二行所以的元素换成12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## numpy 转换

In [32]:
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

## python标量的转换

In [34]:
a = torch.tensor([1.5])
a,a.item(),float(a),int(a)

(tensor([1.5000]), 1.5, 1.5, 1)